<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <Nullable>enable</Nullable>
        <TargetFramework>net48</TargetFramework>
        <Platforms>AnyCPU</Platforms>
        <UseWindowsForms>true</UseWindowsForms>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <LangVersion>10</LangVersion>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <AllowedReferenceRelatedFileExtensions>none</AllowedReferenceRelatedFileExtensions>
        <DebugType>none</DebugType>
        <OutputPath>$(BuildOutputDir)/plugins</OutputPath>
        <GameDeployPath>$(NuclearOptionPluginDeployPath)</GameDeployPath>
        <RootNamespace>NOVR</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\NOVR.XR.OpenXR\NOVR.XR.OpenXR.csproj" Private="false"/>
    </ItemGroup>
    <ItemGroup>
        <Content Include="../third_party/ValveOpenXR/LICENSE.md" Link="Licenses/ValveOpenXR.txt" CopyToOutputDirectory="PreserveNewest" />
        <Content Include="Assets\**\*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>
</Project>
