<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <Nullable>enable</Nullable>
        <TargetFramework>net48</TargetFramework>
        <Platforms>AnyCPU</Platforms>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <LangVersion>10</LangVersion>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <AllowedReferenceRelatedFileExtensions>none</AllowedReferenceRelatedFileExtensions>
        <DebugType>none</DebugType>
        <OutputPath>$(BuildOutputDir)/plugins</OutputPath>
        <GameDeployPath>$(NuclearOptionPluginDeployPath)</GameDeployPath>
        <RootNamespace>NOVR.SteamVr</RootNamespace>
    </PropertyGroup>

    <ItemGroup Condition=" '$(NuclearOptionGameDirResolved)' == 'NUCLEAR_OPTION_NOT_FOUND' ">
        <Reference Include="$(NuclearOptionFallbackLibDir)/*.dll" Exclude="$(NuclearOptionFallbackLibExcludes)">
            <Private>False</Private>
        </Reference>
    </ItemGroup>

    <ItemGroup>
        <Reference Include="System.Runtime.Serialization" />
    </ItemGroup>
</Project>
