<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="Current" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Target Name="BuildProjectReferencesBeforeResolveReferences" BeforeTargets="ResolveReferences" Condition="'@(ProjectReference)' != '' And '$(DesignTimeBuild)' != 'true'">
    <MSBuild
      Projects="@(ProjectReference)"
      Targets="Build"
      Properties="Configuration=$(Configuration);Platform=$(Platform)" />
  </Target>

  <Target Name="StageGameLayout" AfterTargets="Build" Condition="'$(GameDeployPath)' != '' And '$(SkipGameLayoutStaging)' != 'true'">
    <ItemGroup>
      <GameLayoutDeployFiles Include="$(TargetDir)**/*" Exclude="$(TargetDir)Unity.XR.*.dll" />
    </ItemGroup>

    <RemoveDir Directories="$(GameLayoutOutputDir)/$(GameDeployPath)" />
    <MakeDir Directories="$(GameLayoutOutputDir)/$(GameDeployPath)" />
    <Copy
      SourceFiles="@(GameLayoutDeployFiles)"
      DestinationFiles="@(GameLayoutDeployFiles->'$(GameLayoutOutputDir)/$(GameDeployPath)/%(RecursiveDir)%(Filename)%(Extension)')"
      SkipUnchangedFiles="true" />
  </Target>

  <Target Name="DeployToGame" AfterTargets="StageGameLayout" Condition="'$(NovrAutoDeploy)' != 'false' And '$(GameDeployPath)' != '' And '$(NuclearOptionGameDirResolved)' != 'NUCLEAR_OPTION_NOT_FOUND'">
    <ItemGroup>
      <GameDeployFiles Include="$(GameLayoutOutputDir)/$(GameDeployPath)/**/*" />
    </ItemGroup>

    <MakeDir Directories="$(NuclearOptionGameDirResolved)/$(GameDeployPath)" />
    <Copy
      SourceFiles="@(GameDeployFiles)"
      DestinationFiles="@(GameDeployFiles->'$(NuclearOptionGameDirResolved)/$(GameDeployPath)/%(RecursiveDir)%(Filename)%(Extension)')"
      SkipUnchangedFiles="true" />
  </Target>
</Project>
